namespace: hms-prod
replicaCount: 2
image:
  repository: suryaa112003/api-gateway
  tag: stable
  pullPolicy: Always
service:
  type: NodePort
  port: 4000
  nodePort: 30091
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
env:
  PORT: "4000"
  SERVICE_NAME: "api-gateway"
secrets:
  JWT_SECRET: "prod_secret_123"
  INTERNAL_API_KEY: "prod_internal_key"
